export interface ObservableState {
  id: string;
  table: string;
  trigger_field: string;
  trigger_condition: string;
  semantic_meaning: string;
  suggested_task: string;
  priority: "critical" | "high" | "medium" | "low";
}

export interface AIManifest {
  manifest_version: string;
  vertical_id?: string;
  extends?: string;
  description?: string;
  observable_states: ObservableState[];
}

export function mergeManifests(
  core: AIManifest,
  vertical: AIManifest,
): AIManifest {
  // Simple override merge: Vertical states overwrite core states if IDs match
  const stateMap = new Map<string, ObservableState>();

  for (const state of core.observable_states) {
    stateMap.set(state.id, state);
  }

  for (const state of vertical.observable_states) {
    stateMap.set(state.id, state); // overwrites if exists
  }

  return {
    manifest_version: vertical.manifest_version || core.manifest_version,
    vertical_id: vertical.vertical_id,
    extends: vertical.extends,
    description: vertical.description || core.description,
    observable_states: Array.from(stateMap.values()),
  };
}

export function evaluateState(
  state: ObservableState,
  row: Record<string, unknown>,
): boolean {
  const fieldValue = row[state.trigger_field];

  if (state.trigger_condition.startsWith("equals:")) {
    const target = state.trigger_condition.replace("equals:", "").trim();
    return String(fieldValue) === target;
  }

  if (state.trigger_condition === "within_7_days") {
    if (!fieldValue) return false;
    const dateValue = new Date(fieldValue);
    const now = new Date();
    const diffTime = dateValue.getTime() - now.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays >= 0 && diffDays <= 7;
  }

  return false;
}

export function createTask(
  state: ObservableState,
  organizationId: string,
  rowId: string,
) {
  return {
    // We do not specify ID (UUID generated by DB) or user_id (if not strictly needed by RLS)
    vertical_id: "dannflow-default", // This would be dynamic in a real vertical
    title: `Action Required: ${state.suggested_task}`,
    description: `Triggered by ${state.table} (${rowId}). ${state.semantic_meaning}`,
    priority: state.priority,
    triggered_by_state_id: state.id,
    status: "pending",
  };
}
